/** Renders the 1200x630 social share card to public/og.png.
 *
 *  The bounce curve on the card is generated by the real simulator rather than
 *  drawn by hand, so the card can never depict dynamics the project doesn't
 *  actually produce.
 *
 *  Run: npm run make-og  (from the repo root)
 */
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import puppeteer from "puppeteer";

const HERE = dirname(fileURLToPath(import.meta.url));
const { simulate } = await import(
  pathToFileURL(join(HERE, "src/sim/ball.ts")).href
);

const W = 1200;
const H = 630;
// Bottom band only: the curve is a backdrop for the copy, not a chart, so it
// must not run through the headline.
const FLOOR = 566;
// top: the apex of the first arc. Kept below the copy block so the launch
// marker never sits on the subtitle.
const PLOT = { x: 68, w: W - 136, top: 424 };

const cfg = JSON.parse(readFileSync(join(HERE, "public/data/config.json"), "utf8"));
// ~3 s is four clear bounces at e = 0.8. Longer and the tail flattens into a
// straight line across most of the width.
const trace = simulate(1.6, 0, 1, { ...cfg, restitution: 0.8, n_steps: 300 });

const qMax = Math.max(...trace.q);
const toX = (i) => PLOT.x + (i / (trace.q.length - 1)) * PLOT.w;
const toY = (q) => FLOOR - (q / qMax) * (FLOOR - PLOT.top);
const points = trace.q.map((q, i) => `${toX(i).toFixed(1)},${toY(q).toFixed(1)}`).join(" ");

const html = `<!doctype html>
<html><head><meta charset="utf-8"><style>
  @font-face { font-family: x; src: local("Segoe UI"); }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    width: ${W}px; height: ${H}px; overflow: hidden; position: relative;
    background: #0d1117; color: #e6edf3;
    font-family: "Segoe UI", ui-sans-serif, system-ui, sans-serif;
  }
  .glow {
    position: absolute; width: 900px; height: 900px; left: -180px; top: -480px;
    background: radial-gradient(circle, rgba(74,163,223,0.16), transparent 62%);
  }
  .pad { position: absolute; inset: 0; padding: 62px 68px; }
  .kicker {
    display: flex; align-items: center; gap: 12px;
    font-size: 19px; letter-spacing: .16em; text-transform: uppercase; color: #8b949e;
  }
  .mark { width: 17px; height: 17px; border-radius: 50%;
          background: radial-gradient(circle at 33% 30%, #ffe9a8, #e9a23b); }
  h1 { font-size: 62px; line-height: 1.08; letter-spacing: -0.03em; margin-top: 24px; max-width: 17ch; }
  h1 em { font-style: normal; color: #4aa3df; }
  p { margin-top: 20px; font-size: 24px; line-height: 1.45; color: #b6c1cd; max-width: 54ch; }
  .chips { position: absolute; left: 68px; bottom: 44px; display: flex; gap: 13px; }
  .chip {
    display: flex; align-items: center; gap: 9px;
    border: 1px solid #232a33; background: rgba(19,25,32,.82);
    border-radius: 999px; padding: 9px 19px; font-size: 20px; color: #e6edf3;
  }
  .dot { width: 12px; height: 12px; border-radius: 50%; }
  .url { position: absolute; right: 68px; top: 62px; font-size: 20px; color: #6b7590; }
  svg { position: absolute; inset: 0; }
</style></head><body>
  <div class="glow"></div>
  <svg width="${W}" height="${H}">
    <line x1="68" y1="${FLOOR}" x2="${W - 68}" y2="${FLOOR}" stroke="#2c3542" stroke-width="2"/>
    <polyline points="${points}" fill="none" stroke="#e9a23b" stroke-width="3.2"
              stroke-opacity="0.55" stroke-linejoin="round"/>
    <circle cx="${toX(0)}" cy="${toY(trace.q[0]).toFixed(1)}" r="12" fill="#e9a23b"
            fill-opacity="0.9"/>
  </svg>
  <div class="pad">
    <div class="kicker"><span class="mark"></span> Physics-Informed World Models</div>
    <h1>Does a Hamiltonian prior help when physics has <em>contact</em>?</h1>
    <p>HNN vs. Neural ODE vs. MLP on a bouncing ball, where contact breaks
       every smooth flow.</p>
    <div class="chips">
      <div class="chip"><span class="dot" style="background:#1f77b4"></span>MLP</div>
      <div class="chip"><span class="dot" style="background:#d62728"></span>HNN</div>
      <div class="chip"><span class="dot" style="background:#2ca02c"></span>Neural ODE</div>
    </div>
    <div class="url">physics-informed-world-models.vercel.app</div>
  </div>
</body></html>`;

const tmp = join(HERE, "og.tmp.html");
writeFileSync(tmp, html);

const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: W, height: H, deviceScaleFactor: 1 });
await page.goto(pathToFileURL(tmp).href, { waitUntil: "load" });
await page.screenshot({ path: join(HERE, "public/og.png") });
await browser.close();
unlinkSync(tmp);

console.log(`[og] wrote public/og.png (${W}x${H}) from a ${trace.bounceAt.length}-bounce trajectory`);
